### ISSUE TITLE
Terminates immediately at runtime

### ISSUE THREAD

**Issue by AArnott** [vbfox/PInvoke.Forms.Test#3]
There are many exceptions thrown from this callstack (which is odd, since the first one should have killed it, I think):

> {"The specified resource name cannot be found in the image file"}

```
   at ConsoleApplication1.Win32ErrorCheckExtensions.Win32ThrowIfZero(IntPtr ptr) in C:\git\PInvoke.Forms.Test\Win32ErrorCheckExtensions.cs:line 12
   at ConsoleApplication1.Program.CreateDialogParam(SafeLibraryHandle hinst, Int32 iTemplate, IntPtr hwndParent, DialogProc lpDlgProc, IntPtr dwInitParam) in C:\git\PInvoke.Forms.Test\Program.cs:line 22
   at ConsoleApplication1.Program.CreateAndShowDialog() in C:\git\PInvoke.Forms.Test\Program.cs:line 43
   at ConsoleApplication1.Program.Main() in C:\git\PInvoke.Forms.Test\Program.cs:line 37
```

**Comment by vbfox** [comment]
Sorry, I fixed I botched the "resource.h" I committed this morning, it build but something is wrong with it.

I was on my work PC and didn't take the time to test :D took five mins to get a working version back, now it works in ca4f1c801f2459f96158e0e9d9e05c98d820c6e4.
